# ASP.NET Core


# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish $(buildConfiguration)'
  inputs:
    command: publish
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Subskrypcja programu Visual Studio Professional (67e32ba6-63bb-4f67-bf30-e0d5465fe2dc)'
    subscriptionId: '67e32ba6-63bb-4f67-bf30-e0d5465fe2dc'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'devopsNew'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/konradkrzysztofiak/devOps2/master/armTemplates/webApp.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/konradkrzysztofiak/devOps2/master/armTemplates/webApp.parameters.json'
    deploymentMode: 'Incremental'  

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy Azure App Service'
  inputs:
    azureSubscription: '$(Parameters.ConnectedServiceName)'
    appType: webApp
    WebAppName: '$(Parameters.WebAppName)'
